---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.35.35"}]

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  name: winrm
  elevated: true

platforms:
  - name: windows-2012r2
    driver:
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[wisa_customers::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      sql_server:
        server_sa_password: SQL_sa_pa$$w0rd
